apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fcg
resources:
  - k8s/namespace.yaml
  - k8s/apps.yaml
  - k8s/rabbitmq.yaml
  - k8s/mongodb-redis.yaml
  - k8s/kong-gateway.yaml
  - k8s/observability.yaml
configMapGenerator:
  - name: kong-template
    files:
      - kong.yml=kong/kong.yml
      - start.sh=kong/start.sh
  - name: prometheus-config
    files:
      - prometheus.yml=observability/prometheus-k8s.yml
  - name: grafana-datasources
    files:
      - prometheus.yml=observability/grafana/provisioning/datasources/prometheus.yml
  - name: grafana-providers
    files:
      - fcg.yml=observability/grafana/provisioning/dashboards/fcg.yml
  - name: grafana-dashboards
    files:
      - fcg-overview.json=observability/grafana/dashboards/fcg-overview.json
  - name: loki-config
    files:
      - loki.yml=observability/loki.yml
  - name: rabbitmq-definitions
    files:
      - rabbitmq.conf=rabbitmq/rabbitmq.conf
      - definitions.json=rabbitmq/definitions.json
      - start.sh=rabbitmq/start.sh
